export type LegalSpeciality =
    | 'SEXUAL_CRIMES'
    | 'PROPERTY_CRIMES_EMBEZZLEMENT'
    | 'PROPERTY_CRIMES_FRAUD'
    | 'PROPERTY_CRIMES_THEFT'
    | 'PROPERTY_CRIMES_DAMAGE'
    | 'TRAFFIC_ACCIDENT_HIT_RUN'
    | 'TRAFFIC_ACCIDENT_DUI'
    | 'CRIMINAL_PROCEDURE_LAWSUIT'
    | 'CRIMINAL_PROCEDURE_INVESTIGATION'
    | 'ASSAULT_GENERAL'
    | 'ASSAULT_DEFAMATION'
    | 'OTHER_CRIMES_DRUGS'
    | 'OTHER_CRIMES_JUVENILE'
    | 'REAL_ESTATE_GENERAL'
    | 'REAL_ESTATE_REDEVELOPMENT'
    | 'REAL_ESTATE_LEASE'
    | 'FINANCIAL_COMPENSATION'
    | 'FINANCIAL_LOAN'
    | 'FINANCIAL_CONTRACT'
    | 'CIVIL_PROCEDURE_LITIGATION'
    | 'CIVIL_PROCEDURE_SEIZURE'
    | 'FAMILY_DIVORCE'
    | 'FAMILY_INHERITANCE'
    | 'FAMILY_GENERAL'
    | 'CORPORATE_LAW'
    | 'CORPORATE_LABOR'
    | 'MEDICAL_TAX'
    | 'IT_IP_FINANCE';

export const LegalSpecialityLabels: Record<LegalSpeciality, string> = {
    SEXUAL_CRIMES: '성범죄',
    PROPERTY_CRIMES_EMBEZZLEMENT: '횡령/배임',
    PROPERTY_CRIMES_FRAUD: '사기/공갈',
    PROPERTY_CRIMES_THEFT: '절도',
    PROPERTY_CRIMES_DAMAGE: '재물손괴',
    TRAFFIC_ACCIDENT_HIT_RUN: '교통사고/도주',
    TRAFFIC_ACCIDENT_DUI: '음주/무면허',
    CRIMINAL_PROCEDURE_LAWSUIT: '고소/소송절차',
    CRIMINAL_PROCEDURE_INVESTIGATION: '수사/체포/구속',
    ASSAULT_GENERAL: '폭행/협박/상해 일반',
    ASSAULT_DEFAMATION: '명예훼손/모욕',
    OTHER_CRIMES_DRUGS: '마약/도박',
    OTHER_CRIMES_JUVENILE: '소년범죄/학교폭력',
    REAL_ESTATE_GENERAL: '부동산 일반',
    REAL_ESTATE_REDEVELOPMENT: '재개발/재건축',
    REAL_ESTATE_LEASE: '임대차',
    FINANCIAL_COMPENSATION: '손해배상',
    FINANCIAL_LOAN: '대여금/채권추심',
    FINANCIAL_CONTRACT: '계약일반/매매',
    CIVIL_PROCEDURE_LITIGATION: '소송/집행절차',
    CIVIL_PROCEDURE_SEIZURE: '가압류/가처분',
    FAMILY_DIVORCE: '이혼',
    FAMILY_INHERITANCE: '상속',
    FAMILY_GENERAL: '가사 일반',
    CORPORATE_LAW: '기업법무',
    CORPORATE_LABOR: '노동/인사',
    MEDICAL_TAX: '의료/세금/행정',
    IT_IP_FINANCE: 'IT/지식재산/금융'
};